---
- name: route53 grim reaper
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    workshop_dns_zone: rhdemo.io
    max_records: 5
    host_entries: []
    delete_these_entries: []

  tasks:


    - name: delete dns entries marked for deletion
      route53:
        state: "get"
        zone: "{{workshop_dns_zone}}"
        record: "student1.0471.rhdemo.io"
        type: A
        value: "18.196.157.35"
      register: outputforthis

    - name: grab all record sets
      debug:
        msg: "{{outputforthis}}"
